pipeline {
    agent any
    
    environment {
        BUILD_NUMBER = "${params.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout (CI)') {
            steps {
                git url: "https://github.com/abhradippaul/DevSecOps-Projects.git", branch: "project1"
            }
        }
        stage('SonarQube Code Analysis (CI)') {
             agent {
                        docker {
                            image "abhradippaul/devsecops-project1"
                            args "--user root -v /var/run/docker.sock:/var/run/docker.sock"
                        }
                    }
                steps {
                    script {
                        withSonarQubeEnv('sonar-scanner') {
                            sh "cd Project1 && sonar-scanner -Dsonar.projectName=devsecops_project1 -Dsonar.projectKey=devsecops_project1"
                        }
                    }
                }
          }
             stage("SonarQube Quality Gate Check (CI)") {
                steps {
                    script {
                    def qualityGate = waitForQualityGate()
                        
                        if (qualityGate.status != 'OK') {
                            echo "${qualityGate.status}"
                            error "Quality Gate failed: ${qualityGateStatus}"
                        }
                        else {
                            echo "${qualityGate.status}"
                            echo "SonarQube Quality Gates Passed"
                        }
                    }
                }
        }
        stage("Test the filesystem (CI)") {
            steps {
                parallel(
                  "FRONTEND": {
                    sh "cd Project1/frontend && docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /reports:/root/trivy-reports -v ~/.cache:/root/.cache  alpine/trivy fs -f table -o /root/trivy-reports/frontend-filesystem-scan ."
                  },
                  "BACKEND": {
                    sh "cd Project1/backend && docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /reports:/root/trivy-reports -v ~/.cache:/root/.cache alpine/trivy fs -f table -o /root/trivy-reports/backend-filesystem-scan ."
                  }
                )
            }
        }
        stage ("OWASP (CI)") {
            agent {
                        docker {
                            image "abhradippaul/node-owasp"
                            args "--user root -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/dependency-check:/tmp/dependency-check -v /home/abhradip_paul/.dependency-check:/root/.dependency-check"
                        }
                    }
            steps { 
                parallel(
                  "FRONTEND": {
                    sh "cd Project1/frontend && npm install"
                    sh '/tmp/dependency-check/bin/dependency-check.sh --scan Project1/frontend --data /root/.dependency-check --out /reports/frontend-owasp-report'
                  },
                  "BACKEND": {
                    sh "cd Project1/backend && npm install"
                    sh '/tmp/dependency-check/bin/dependency-check.sh --scan Project1/backend --data /root/.dependency-check --out /reports/backend-owasp-report'
                  }
                )
                
            }
        }
        stage("Build And Test image (CI)") {
            steps {
                parallel(
                  "FRONTEND": {
                    sh "cd Project1/frontend && docker build -t abhradippaul/devsecops-project1-frontend:${BUILD_NUMBER} ."
                    sh "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /reports:/root/trivy-reports -v ~/.cache:/root/.cache  alpine/trivy image -f table -o /root/trivy-reports/frontend-image-scan abhradippaul/devsecops-project1-frontend:${BUILD_NUMBER}"
                  },
                  "BACKEND": {
                    sh "cd Project1/backend && docker build -t abhradippaul/devsecops-project1-backend:${BUILD_NUMBER} ."
                    sh "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /reports:/root/trivy-reports -v ~/.cache:/root/.cache alpine/trivy image -f table -o /root/trivy-reports/backend-image-scan abhradippaul/devsecops-project1-backend:${BUILD_NUMBER}"
                  }
                )
            }
        }
        stage("Docker login (CI)") {
            steps {
                withCredentials([
                        usernamePassword(credentialsId: "dockerhub-jenkins",
                        usernameVariable: "username", 
                        passwordVariable: "password")]) {
                            sh "docker login -u $username -p $password"
                }
            }
        }
        stage("Push the image (CI)") {
            steps {
            parallel(
                  "FRONTEND": {
                    sh "docker push abhradippaul/devsecops-project1-frontend:${BUILD_NUMBER}"
                  },
                  "BACKEND": {
                    sh "docker push abhradippaul/devsecops-project1-backend:${BUILD_NUMBER}"
                  }
                )
        }
    }
        stage("GitHub commit (CI)") {
            steps {
                withCredentials([
                    usernamePassword(
                    credentialsId: "github-jenkins", 
                    usernameVariable: "username", 
                    passwordVariable: "password"
                    )]){
                        sh '''
                                git config user.email "abhradipserampore@gmail.com"
                                git config user.name "${username}"
                                cd Project1
                                cp template/frontend.yaml manifests/frontend.yaml
                                cp template/backend.yaml manifests/backend.yaml
                                sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" manifests/frontend.yaml
                                sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" manifests/backend.yaml
                                git add manifests
                                git commit -m "Update deployment image to version ${BUILD_NUMBER}"
                                git push https://{username}:${password}@github.com/${username}/DevSecOps-Projects.git
                                '''                  
                }
            }
        }
    }
}