apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend-service
  namespace: devsecops-project1
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 31101
  selector:
    app: backend
  type: NodePort
status:
  loadBalancer: {}