apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: devsecops-project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: abhradippaul/devsecops-project1-backend:v1
          name: backend
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-cm
            - secretRef:
                name: backend-secret
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "200Mi"