apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend-service
  namespace: devsecops-project1
spec:
  ports:
  - port: 5173
    nodePort: 31100
    protocol: TCP
    targetPort: 5173
  selector:
    app: frontend
  type: NodePort
status:
  loadBalancer: {}