apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: devsecops-project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: cloudacademydevops/frontend:v1
        name: frontend
        ports:
          - containerPort: 5173
        env:
          - name: VITE_API_PATH
            value: http://35.238.42.194:31100
        resources: 
          requests: 
            cpu: "50m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "200Mi"