apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: devsecops-project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: abhradippaul/devsecops-project1-frontend:v1
          name: frontend
          ports:
            - containerPort: 5173
          envFrom:
            - configMapRef:
                name: frontend-cm
          resources:
            requests:
              cpu: "25m"
              memory: "50Mi"
            limits:
              cpu: "50m"
              memory: "100Mi"
